// frontend_nextjs/src/app/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import GameBoard from '@/components/GameBoard';
import GameControls from '@/components/GameControls';
import { GameApi } from '@/lib/api';
import { GameState, Player } from '@/types';
import '@/styles/App.css';

export default function Home() {
  const [gameState, setGameState] = useState<GameState | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [aiOpponentEnabled, setAiOpponentEnabled] = useState<boolean>(false);
  const [aiDifficulty, setAiDifficulty] = useState<string>('medium');
  const [boardSize, setBoardSize] = useState<number>(19);
  const [aiPassNotification, setAiPassNotification] = useState<boolean>(false);

  useEffect(() => {
    loadGameState();
  }, []);

  const loadGameState = async () => {
    try {
      setLoading(true);
      setError(null);
      const state = await GameApi.getGameState();
      setGameState(state);
    } catch (err) {
      setError('Failed to load game state');
      console.error('Error loading game state:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleMove = async (row: number, col: number) => {
    if (!gameState) return;

    try {
      setError(null);
      setAiPassNotification(false);
      const response = await GameApi.makeMove(row, col);
      setGameState(response.game_state);

      // Auto-play AI move after a short delay if enabled and game hasn't ended
      if (
        aiOpponentEnabled &&
        response.game_state.current_player === Player.WHITE &&
        !response.game_state.game_ended
      ) {
        setTimeout(() => {
          handleAiMove(aiDifficulty);
        }, 1000);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to make move');
      console.error('Error making move:', err);
    }
  };

  const handleAiMove = async (difficulty: string) => {
    try {
      const response = await GameApi.aiMove(difficulty);
      setGameState(response.game_state);
      if (response.ai_passed) {
        setAiPassNotification(true);
        setTimeout(() => {
          setAiPassNotification(false);
        }, 3000);
      }
    } catch (err) {
      setError('Failed to make AI move');
      console.error('Error making AI move:', err);
    }
  };

  const handlePass = async () => {
    try {
      setError(null);
      const response = await GameApi.pass();
      setGameState(response.game_state);
    } catch (err) {
      setError('Failed to pass turn');
      console.error('Error passing turn:', err);
    }
  };

  const handleNewGame = async (newBoardSize?: number) => {
    try {
      setError(null);
      setAiPassNotification(false);
      const size = newBoardSize || boardSize;
      const response = await GameApi.newGame(size);
      setGameState(response.game_state);
      setBoardSize(size);
    } catch (err) {
      setError('Failed to start new game');
      console.error('Error starting new game:', err);
    }
  };

  const handleReset = async () => {
    try {
      setError(null);
      setAiPassNotification(false);
      const response = await GameApi.resetGame();
      setGameState(response.game_state);
    } catch (err) {
      setError('Failed to reset game');
      console.error('Error resetting game:', err);
    }
  };

  const handleBoardSizeChange = async (newSize: number) => {
    setBoardSize(newSize);
    await handleNewGame(newSize);
  };

  const toggleAiOpponent = () => {
    setAiOpponentEnabled(!aiOpponentEnabled);
  };

  if (loading) {
    return (
      <div className="app">
        <div className="loading">Loading game...</div>
      </div>
    );
  }

  if (!gameState) {
    return (
      <div className="app">
        <div className="error">
          {error || 'Failed to load game'}
          <button onClick={loadGameState}>Retry</button>
        </div>
      </div>
    );
  }

  return (
    <div className="app">
      <div className="app-header">
        <h1>Go Game - Next.js</h1>
        {error && <div className="error-message">{error}</div>}
        {aiPassNotification && (
          <div className="ai-pass-notification">
            🤖 AI Opponent passed their turn
          </div>
        )}
      </div>

      <div className="game-container">
        <GameControls
          currentPlayer={gameState.current_player}
          capturedStones={gameState.captured_stones}
          onPass={handlePass}
          onNewGame={handleNewGame}
          onReset={handleReset}
          aiOpponentEnabled={aiOpponentEnabled}
          onToggleAi={toggleAiOpponent}
          aiDifficulty={aiDifficulty}
          onSetAiDifficulty={setAiDifficulty}
          onAiMove={handleAiMove}
          boardSize={boardSize}
          onSetBoardSize={handleBoardSizeChange}
          gameEnded={gameState.game_ended || false}
          consecutivePasses={gameState.consecutive_passes || 0}
        />

        <GameBoard
          board={gameState.board}
          onMove={handleMove}
          currentPlayer={gameState.current_player}
        />
      </div>
    </div>
  );
}

// frontend_angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameBoardComponent } from './game-board/game-board';
import { GameControlsComponent } from './game-controls/game-controls';
import { GameApiService } from './game-api.service';
import { GameState, Player } from './types';

@Component({
  selector: 'app-root',
  imports: [CommonModule, GameBoardComponent, GameControlsComponent],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App implements OnInit {
  gameState: GameState | null = null;
  loading = true;
  error: string | null = null;
  aiOpponentEnabled = false;
  aiDifficulty = 'medium';
  boardSize = 19;
  aiPassNotification = false;

  constructor(private gameApiService: GameApiService) {}

  ngOnInit() {
    this.loadGameState();
  }

  loadGameState() {
    this.loading = true;
    this.error = null;
    this.gameApiService.getGameState().subscribe({
      next: (state) => {
        this.gameState = state;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load game state';
        this.loading = false;
        console.error('Error loading game state:', err);
      }
    });
  }

  handleMove(event: {row: number, col: number}) {
    if (!this.gameState) return;

    this.error = null;
    this.aiPassNotification = false;
    
    this.gameApiService.makeMove(event.row, event.col).subscribe({
      next: (response) => {
        this.gameState = response.game_state;
        
        // Auto-play AI move after a short delay if enabled and game hasn't ended
        if (
          this.aiOpponentEnabled &&
          response.game_state.current_player === Player.WHITE &&
          !response.game_state.game_ended
        ) {
          setTimeout(() => {
            this.handleAiMove(this.aiDifficulty);
          }, 1000);
        }
      },
      error: (err) => {
        this.error = err.error?.detail || 'Failed to make move';
        console.error('Error making move:', err);
      }
    });
  }

  handleAiMove(difficulty: string) {
    this.gameApiService.aiMove(difficulty).subscribe({
      next: (response) => {
        this.gameState = response.game_state;
        if (response.ai_passed) {
          this.aiPassNotification = true;
          setTimeout(() => {
            this.aiPassNotification = false;
          }, 3000);
        }
      },
      error: (err) => {
        this.error = 'Failed to make AI move';
        console.error('Error making AI move:', err);
      }
    });
  }

  handlePass() {
    this.error = null;
    this.gameApiService.pass().subscribe({
      next: (response) => {
        this.gameState = response.game_state;
      },
      error: (err) => {
        this.error = 'Failed to pass turn';
        console.error('Error passing turn:', err);
      }
    });
  }

  handleNewGame(newBoardSize?: number) {
    this.error = null;
    this.aiPassNotification = false;
    const size = newBoardSize || this.boardSize;
    
    this.gameApiService.newGame(size).subscribe({
      next: (response) => {
        this.gameState = response.game_state;
        this.boardSize = size;
      },
      error: (err) => {
        this.error = 'Failed to start new game';
        console.error('Error starting new game:', err);
      }
    });
  }

  handleReset() {
    this.error = null;
    this.aiPassNotification = false;
    
    this.gameApiService.resetGame().subscribe({
      next: (response) => {
        this.gameState = response.game_state;
      },
      error: (err) => {
        this.error = 'Failed to reset game';
        console.error('Error resetting game:', err);
      }
    });
  }

  handleBoardSizeChange(newSize: number) {
    this.boardSize = newSize;
    this.handleNewGame(newSize);
  }

  toggleAiOpponent() {
    this.aiOpponentEnabled = !this.aiOpponentEnabled;
  }

  setAiDifficulty(difficulty: string) {
    this.aiDifficulty = difficulty;
  }

  // Expose Player enum to template
  Player = Player;
}
